package views;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import services.AccountService;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author leminhung
 */
public class MenuGiangVien_Form extends javax.swing.JFrame {

    /**
     * Creates new form MenuGiangVien_Form
     */
    public MenuGiangVien_Form() {
        initComponents();
        lblXinChao.setText("Xin chào " + AccountService.getTenNDByMaND(DangNhap_Form.maNDHT));
        Image image = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/haui-logo.jpg"));
        setIconImage(image);
        this.getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        btnDangKyPhong = new javax.swing.JButton();
        btnXemCTPhong = new javax.swing.JButton();
        lblXinChao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel1.setText("Menu giảng viên");

        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton7.setText("Đăng xuất");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DangXuat_ActionPerformed(evt);
            }
        });

        btnDangKyPhong.setBackground(new java.awt.Color(244, 244, 244));
        btnDangKyPhong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDangKyPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dangky.png"))); // NOI18N
        btnDangKyPhong.setText("Đăng ký phòng học");
        btnDangKyPhong.setAlignmentX(0.5F);
        btnDangKyPhong.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDangKyPhong.setIconTextGap(0);
        btnDangKyPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XemPhong_ActionPerformed(evt);
            }
        });

        btnXemCTPhong.setBackground(new java.awt.Color(244, 244, 244));
        btnXemCTPhong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnXemCTPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lich.png"))); // NOI18N
        btnXemCTPhong.setText("Xem chi tiết phòng học");
        btnXemCTPhong.setIconTextGap(0);
        btnXemCTPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemCTPhongActionPerformed(evt);
            }
        });

        lblXinChao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblXinChao.setText("Xin chào bạn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(btnDangKyPhong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btnXemCTPhong)
                .addGap(58, 58, 58))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(309, 309, 309))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(441, 441, 441)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lblXinChao, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblXinChao)
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDangKyPhong)
                    .addComponent(btnXemCTPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DangXuat_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DangXuat_ActionPerformed
        DangNhap_Form dangNhapForm = new DangNhap_Form();
        this.dispose();
        dangNhapForm.setVisible(true);
    }//GEN-LAST:event_DangXuat_ActionPerformed

    private void XemPhong_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XemPhong_ActionPerformed
        try {
            DangKyPhong_Form dangKyForm = new DangKyPhong_Form();
            this.dispose();
            dangKyForm.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MenuGiangVien_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_XemPhong_ActionPerformed

    private void btnXemCTPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemCTPhongActionPerformed
        try {
            XemPhongHoc_Form xemPhongHoc = new XemPhongHoc_Form();
            this.dispose();
            xemPhongHoc.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MenuGiangVien_Form.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnXemCTPhongActionPerformed

    public static void displayMenu() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGiangVien_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGiangVien_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGiangVien_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGiangVien_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGiangVien_Form().setVisible(true);
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        displayMenu();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangKyPhong;
    private javax.swing.JButton btnXemCTPhong;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblXinChao;
    // End of variables declaration//GEN-END:variables
}
