package views;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import services.AccountService;

/**
 *
 * @author leminhung
 */
public class MenuQuanTri_Form extends javax.swing.JFrame {

    /**
     * Creates new form MenuQuanTri_Form
     */
    public MenuQuanTri_Form() {
        initComponents();
        lblXinChao.setText("Xin chào " + AccountService.getTenNDByMaND(DangNhap_Form.maNDHT));
        Image image = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/haui-logo.jpg"));
        setIconImage(image);
        this.getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnQuanTriCoSo = new javax.swing.JButton();
        btnQuanTriDayNha = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        lblXinChao = new javax.swing.JLabel();
        btnTaoTaiKhoanGiangVien = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel1.setText("Menu quản trị");

        btnQuanTriCoSo.setBackground(new java.awt.Color(244, 244, 244));
        btnQuanTriCoSo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnQuanTriCoSo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tang.png"))); // NOI18N
        btnQuanTriCoSo.setText("Quản trị cơ sở");
        btnQuanTriCoSo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuanTriCoSo_ActionPerformed(evt);
            }
        });

        btnQuanTriDayNha.setBackground(new java.awt.Color(244, 244, 244));
        btnQuanTriDayNha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnQuanTriDayNha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/daynha.png"))); // NOI18N
        btnQuanTriDayNha.setText("Quản trị dãy nhà");
        btnQuanTriDayNha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuanTriDayNha_ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(244, 244, 244));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/coso.png"))); // NOI18N
        jButton4.setText("Quản trị tầng");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuanTriTang_ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(244, 244, 244));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/phong.png"))); // NOI18N
        jButton5.setText("Quản trị phòng");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuanTriPhong_ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(244, 244, 244));
        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton7.setText("Đăng xuất");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DangXuat_ActionPerformed(evt);
            }
        });

        lblXinChao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblXinChao.setText("Xin chào bạn");

        btnTaoTaiKhoanGiangVien.setBackground(new java.awt.Color(244, 244, 244));
        btnTaoTaiKhoanGiangVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTaoTaiKhoanGiangVien.setText("Tạo tài khoản giảng viên");
        btnTaoTaiKhoanGiangVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoTaiKhoanGiangVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(327, 327, 327))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblXinChao, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnQuanTriCoSo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQuanTriDayNha, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99))
            .addGroup(layout.createSequentialGroup()
                .addGap(308, 308, 308)
                .addComponent(btnTaoTaiKhoanGiangVien)
                .addGap(40, 40, 40)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblXinChao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuanTriCoSo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuanTriDayNha, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTaoTaiKhoanGiangVien, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QuanTriCoSo_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuanTriCoSo_ActionPerformed
        QuanTriCoSo_Form qtCoSo =new QuanTriCoSo_Form();
        this.dispose();
        qtCoSo.setVisible(true);
    }//GEN-LAST:event_QuanTriCoSo_ActionPerformed

    private void QuanTriTang_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuanTriTang_ActionPerformed
        QuanTriTang_Form.displayMenu();
        dispose();
    }//GEN-LAST:event_QuanTriTang_ActionPerformed

    private void QuanTriPhong_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuanTriPhong_ActionPerformed
        QuanTriPhong_Form Qtform;
        try {
            Qtform = new QuanTriPhong_Form();
            this.dispose();
            Qtform.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MenuQuanTri_Form.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_QuanTriPhong_ActionPerformed

    private void DangXuat_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DangXuat_ActionPerformed
        DangNhap_Form dangNhapForm = new DangNhap_Form();
        this.dispose();
        dangNhapForm.setVisible(true);
    }//GEN-LAST:event_DangXuat_ActionPerformed

    private void QuanTriDayNha_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuanTriDayNha_ActionPerformed
        QuanTriDayNha_Form qtCoSo =new QuanTriDayNha_Form();
        this.dispose();
        qtCoSo.setVisible(true);
    }//GEN-LAST:event_QuanTriDayNha_ActionPerformed

    private void btnTaoTaiKhoanGiangVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoTaiKhoanGiangVienActionPerformed
        DangKy_Form dkForm = new DangKy_Form();
        dkForm.setVisible(true);
    }//GEN-LAST:event_btnTaoTaiKhoanGiangVienActionPerformed

    public static void displayMenu() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuQuanTri_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuQuanTri_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuQuanTri_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuQuanTri_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuQuanTri_Form().setVisible(true);
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        displayMenu();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuanTriCoSo;
    private javax.swing.JButton btnQuanTriDayNha;
    private javax.swing.JButton btnTaoTaiKhoanGiangVien;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblXinChao;
    // End of variables declaration//GEN-END:variables
}
