/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.ChiTietPhongHoc;
import models.CoSo;
import models.DayNha;
import models.Phong;
import models.Tang;
import services.ChiTietPhongService;
import services.CoSoService;
import services.DayNhaService;
import services.PhongService;
import services.TangService;

/**
 *
 * @author DELL Latitude 5570
 */
public class XemPhongHoc_Form extends javax.swing.JFrame {

    DefaultTableModel tableModel;
    
    CoSoService coSoService = new CoSoService();
    DayNhaService dayNhaService = new DayNhaService();
    TangService tangService = new TangService();
    PhongService PhongService = new PhongService();
    ChiTietPhongService chiTietPhongService = new ChiTietPhongService();

    /**
     * Creates new form XemPhongHocForm
     *
     * @throws java.sql.SQLException
     */
    public XemPhongHoc_Form() throws SQLException {
        initComponents();

        tableModel = (DefaultTableModel) tblCTPhong.getModel();
        showComboData();
        
        Image image = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/haui-logo.jpg"));
        setIconImage(image);
        this.getContentPane().setBackground(Color.getHSBColor(0.0f, 0.0f, 0.9f));
    }

    private void showComboData() throws SQLException {
        List<CoSo> dsCoSo = CoSoService.readAllCoSo();
        for (CoSo coSo : dsCoSo) {
            cbCoSo.addItem(coSo.getMaCoSo());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbCoSo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbDayNha = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbTang = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbPhongHoc = new javax.swing.JComboBox<>();
        btnXemCT = new javax.swing.JButton();
        btnXemLichPhongTrongTuan = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTietBatDau = new javax.swing.JTextField();
        txtTietKetThuc = new javax.swing.JTextField();
        btnKiemTra = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        dcNgay = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCTPhong = new javax.swing.JTable();
        btnHome1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Xem phòng học");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Xem chi tiết phòng học", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 20))); // NOI18N
        jPanel1.setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Cơ sở:");

        cbCoSo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbCoSo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCoSoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Dãy nhà:");

        cbDayNha.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbDayNha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDayNhaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Tầng:");

        cbTang.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbTang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTangActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Phòng học:");

        cbPhongHoc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbPhongHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPhongHocActionPerformed(evt);
            }
        });

        btnXemCT.setBackground(new java.awt.Color(244, 244, 244));
        btnXemCT.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnXemCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye-icon.png"))); // NOI18N
        btnXemCT.setText("Xem chi tiết");
        btnXemCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemCTActionPerformed(evt);
            }
        });

        btnXemLichPhongTrongTuan.setBackground(new java.awt.Color(244, 244, 244));
        btnXemLichPhongTrongTuan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnXemLichPhongTrongTuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Date.png"))); // NOI18N
        btnXemLichPhongTrongTuan.setText("Xem lịch phòng trong tuần");
        btnXemLichPhongTrongTuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemLichPhongTrongTuanActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Kiểm tra trạng thái phòng"));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Tiết kết thúc:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Tiết bắt đầu:");

        btnKiemTra.setBackground(new java.awt.Color(244, 244, 244));
        btnKiemTra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tick.png"))); // NOI18N
        btnKiemTra.setText("Kiểm tra");
        btnKiemTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKiemTraActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Ngày:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(60, 60, 60)
                        .addComponent(dcNgay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTietKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(15, 15, 15)
                        .addComponent(txtTietBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKiemTra)
                .addGap(166, 166, 166))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(dcNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTietBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTietKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(btnKiemTra, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(21, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbTang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbDayNha, 0, 289, Short.MAX_VALUE)
                            .addComponent(cbPhongHoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbCoSo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnXemLichPhongTrongTuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXemCT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(109, 109, 109))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbCoSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbDayNha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbTang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cbPhongHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnXemCT, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXemLichPhongTrongTuan, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblCTPhong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblCTPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Phòng", "Ngày", "Tiết bắt đầu", "Tiết kết thúc", "Giáo viên đăng ký"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCTPhong.setRowHeight(32);
        tblCTPhong.setShowGrid(false);
        jScrollPane1.setViewportView(tblCTPhong);
        if (tblCTPhong.getColumnModel().getColumnCount() > 0) {
            tblCTPhong.getColumnModel().getColumn(0).setMinWidth(100);
            tblCTPhong.getColumnModel().getColumn(0).setMaxWidth(110);
            tblCTPhong.getColumnModel().getColumn(1).setMinWidth(120);
            tblCTPhong.getColumnModel().getColumn(1).setMaxWidth(140);
            tblCTPhong.getColumnModel().getColumn(2).setMinWidth(85);
            tblCTPhong.getColumnModel().getColumn(2).setMaxWidth(100);
            tblCTPhong.getColumnModel().getColumn(3).setMinWidth(85);
            tblCTPhong.getColumnModel().getColumn(3).setMaxWidth(100);
            tblCTPhong.getColumnModel().getColumn(4).setMinWidth(120);
        }

        btnHome1.setBackground(new java.awt.Color(244, 244, 244));
        btnHome1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Home.png"))); // NOI18N
        btnHome1.setText("Trang chủ");
        btnHome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHome1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(btnHome1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXemCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemCTActionPerformed
        try {
            String selectedItemTenPhong = (String) cbPhongHoc.getSelectedItem();
            ArrayList<ChiTietPhongHoc> dsCTPhong = ChiTietPhongService.getDsCTPhongHocTheoTenPhong(selectedItemTenPhong);
            tableModel.setRowCount(0);
            if(dsCTPhong.isEmpty()){
                JOptionPane.showMessageDialog(null, "Phòng học trống", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }

            for (ChiTietPhongHoc ctPhong : dsCTPhong) {
                tableModel.addRow(new Object[]{selectedItemTenPhong, 
                    ctPhong.getNgay(), ctPhong.getTietHocBatDau(), 
                    ctPhong.getTietHocKetThuc(), ctPhong.getTenND()});
            }
        } catch (SQLException ex) {
            Logger.getLogger(XemPhongHoc_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnXemCTActionPerformed

    private void cbCoSoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCoSoActionPerformed

        cbDayNha.removeAllItems();
        String selectedItemMaCoSo = (String) cbCoSo.getSelectedItem();
        List<DayNha> dsDayNha = DayNhaService.readAllDayNhaTheoCoSo(selectedItemMaCoSo);
        for (DayNha dayNha : dsDayNha) {
            cbDayNha.addItem(dayNha.getMaDayNha());
        }
    }//GEN-LAST:event_cbCoSoActionPerformed

    private void cbDayNhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDayNhaActionPerformed
        cbTang.removeAllItems();
        String selectedItemMaDayNha = (String) cbDayNha.getSelectedItem();
        List<Tang> dsTang = TangService.readAllTangTheoDayNha(selectedItemMaDayNha);
        for (Tang tang : dsTang) {
            cbTang.addItem(tang.getTenTang());
        }
    }//GEN-LAST:event_cbDayNhaActionPerformed

    private void cbTangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTangActionPerformed
        try {
            cbPhongHoc.removeAllItems();
            String selectedItemTenTang = (String) cbTang.getSelectedItem();
            ArrayList<Phong> dsPhong = PhongService.getDsPhongTheoTenTang(selectedItemTenTang);
            for (Phong phong : dsPhong) {
                cbPhongHoc.addItem(phong.getTenPhong());
            }
        } catch (SQLException ex) {
            Logger.getLogger(XemPhongHoc_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbTangActionPerformed

    private void cbPhongHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPhongHocActionPerformed

    }//GEN-LAST:event_cbPhongHocActionPerformed

    private void btnXemLichPhongTrongTuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemLichPhongTrongTuanActionPerformed
        String selectedItemTenPhong = (String) cbPhongHoc.getSelectedItem();

        XemLichPhong_Form lichPhong = new XemLichPhong_Form(this, rootPaneCheckingEnabled);
        lichPhong.LoadLich(selectedItemTenPhong);
        lichPhong.setVisible(true);
    }//GEN-LAST:event_btnXemLichPhongTrongTuanActionPerformed

    private void btnKiemTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKiemTraActionPerformed
        try {
            // Kiểm tra rỗng các trường 
            if (dcNgay.getDate() == null || "".equals(txtTietBatDau.getText()) || "".equals(txtTietKetThuc.getText())) {
                throw new Exception("Vui lòng điền đầy đủ thông tin");
            }
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            String date = format.format(dcNgay.getDate());

            String selectedItemTenPhong = (String) cbPhongHoc.getSelectedItem();
            ArrayList<ChiTietPhongHoc> dsCTPhong = ChiTietPhongService.getDsCTPhongHocTheoNgayVaTenPhong(date, selectedItemTenPhong);
            int tietBD = Integer.parseInt(txtTietBatDau.getText());
            int tietKT = Integer.parseInt(txtTietKetThuc.getText());

            // Kiểm tra hợp lệ của tiết học
            if (tietBD <= 0 || tietBD > 16 || tietKT <= 0 || tietKT > 16) {
                throw new Exception("Tiết chỉ nằm trong khoảng 1 đến 16");
            }
            if (tietBD >= tietKT) {
                throw new Exception("Tiết bắt đầu phải nhỏ hơn tiết kết thúc");
            }

            // Kiểm tra phòng trống hay đã được đăng ký
            boolean trong = true;
            for (ChiTietPhongHoc ctPhong : dsCTPhong) {
                if (tietKT >= ctPhong.getTietHocBatDau() && tietKT <= ctPhong.getTietHocKetThuc()) {
                    trong = false;
                }
                if (tietBD >= ctPhong.getTietHocBatDau() && tietBD <= ctPhong.getTietHocKetThuc()) {
                    trong = false;
                }
                if (tietBD <= ctPhong.getTietHocBatDau() && tietKT >= ctPhong.getTietHocKetThuc()) {
                    trong = false;
                }
            }
            if (trong) {
                JOptionPane.showMessageDialog(null, "Phòng trống trong những tiết trên", "Kiểm tra phòng", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Phòng đã được đăng ký trong những tiết trên", "Kiểm tra phòng", JOptionPane.INFORMATION_MESSAGE);
            } 

        } catch (SQLException ex) {
            Logger.getLogger(XemPhongHoc_Form.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnKiemTraActionPerformed

    private void btnHome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome1ActionPerformed
        MenuGiangVien_Form gvMenu = new MenuGiangVien_Form();
        this.dispose();
        gvMenu.setVisible(true);
    }//GEN-LAST:event_btnHome1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XemPhongHoc_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XemPhongHoc_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XemPhongHoc_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XemPhongHoc_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new XemPhongHoc_Form().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(XemPhongHoc_Form.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome1;
    private javax.swing.JButton btnKiemTra;
    private javax.swing.JButton btnXemCT;
    private javax.swing.JButton btnXemLichPhongTrongTuan;
    private javax.swing.JComboBox<String> cbCoSo;
    private javax.swing.JComboBox<String> cbDayNha;
    private javax.swing.JComboBox<String> cbPhongHoc;
    private javax.swing.JComboBox<String> cbTang;
    private com.toedter.calendar.JDateChooser dcNgay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCTPhong;
    private javax.swing.JTextField txtTietBatDau;
    private javax.swing.JTextField txtTietKetThuc;
    // End of variables declaration//GEN-END:variables

}
